FROM rackattack-nas.dc1:5000/dev-base:8783e1542632ab723a427b54cd30ced12ff52d4e

COPY dev-requirements.txt /tmp/dev-requirements.txt
RUN pip install --no-cache-dir -r /tmp/dev-requirements.txt

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY strato-requirements.txt /tmp/strato-requirements.txt
RUN pip install --no-cache-dir -r /tmp/strato-requirements.txt

COPY etc/ /usr/share/srv1/etc/
