---

srv1-worker:
  image: rackattack-nas.dc1:5000/staging/srv1:latest
  container_name: srv1-worker.service.strato
  dns_search: service.strato
  entrypoint:
    - celery
    - worker
    - --app=srv1.celery_app:app
    - --loglevel=INFO
    - --hostname=srv1@%h
    - --concurrency=100
    - --pool=gevent
  volumes:
    - /etc/stratoscale/:/etc/stratoscale/:ro
    - /etc/localtime:/etc/localtime:ro
  net: "host"
